### ISSUE TITLE
[Suggestion] Add support for calculating multiple items at once

### ISSUE THREAD

**Issue by Bmandk** [GTNewHorizons/JustEnoughCalculation#13]
It's not uncommon to want to craft multiple items in one go, and being able to batch craft all the steps together would help reduce the steps needed instead of crafting each item by itself.

As a simplified example with vanilla Minecraft, if I want to craft say 4 pistons and 2 chests, that in turn requires a total of 28 planks, which would in turn translate to crafting 7 logs into planks. Using the calculator, I'd have to do the log->planks step two times since I'm unable to batch calculate those.

This is of course a very simplified example compared to GTNH, but you can imagine how the steps can become more complex and how batch crafting can save time.

If you're open to this, I might take a stab at implementing this myself. My suggestion for the design would be to add a second row of items (above history) that is the "current batch". Left-clicking a slot would put that in the main slot like currently, so you can edit the amounts (which will also be shown in the row like all the other items). Right clicking would remove an item from the current batch. 

I created a quick mockup of the idea below, although note that the input-items aren't correct, couldn't be bothered to do that.

![image](https://github.com/user-attachments/assets/8e9a24ab-ce43-4ddb-84b6-28d3b2d31647)

Let me know if you think this is a good idea, and I can get started on it.

**Comment by PlayfulPiano** [comment]
That would be a really nice addition for the mod. There's also other suggestions I've made in the repo for similar mod improvements if you want to take a look at them.

Good luck with coding any changes though, I've heard that the code is somewhat difficult to decipher.
