### ISSUE TITLE
Is there a technical reason why the calculator doens't import recipes from JEI automatically?

### ISSUE THREAD

**Issue by mainrs** [GTNewHorizons/JustEnoughCalculation#17]
Having to add every single recipe I want to calculate it kind of cumbersome :( I was wondering what the reason behind this decision was.

**Comment by PlayfulPiano** [comment]
There are multiple recipes for the same item output, some with cheaper or more expensive costs to generate. It would be extremely difficult if not impossible to have the mod automatically pick the correct recipe path for an item or specifically modulate the recipes based on what stage of the game you're in.

The best that can be done with this type of mod is have a set of default recipes pre loaded (emi does this), but even then that's usually limited to vanilla recipes as mod recipes are usually modpack specific.

E.g. iron ingots to iron plates either require a hammer and 2 ingots in a crafting table (stone age), 3 ingots in a forge hammer for 2 plates (steam age), or 1 ingot in a bender for 1 plate (LV). How would the mod calculate the recipe correctly here?


The only alternative is to preload everything but include a default recipe system that requires manual enabling. That might be a little better for the user, but similarly that would be pretty complex on the development side.

**Comment by mainrs** [comment]
> There are multiple recipes for the same item output, some with cheaper or more expensive costs to generate. It would be extremely difficult if not impossible to have the mod automatically pick the correct recipe path for an item or specifically modulate the recipes based on what stage of the game you're in.
> 
> The best that can be done with this type of mod is have a set of default recipes pre loaded (emi does this), but even then that's usually limited to vanilla recipes as mod recipes are usually modpack specific.
> 
> E.g. iron ingots to iron plates either require a hammer and 2 ingots in a crafting table (stone age), 3 ingots in a forge hammer for 2 plates (steam age), or 1 ingot in a bender for 1 plate (LV). How would the mod calculate the recipe correctly here?
> 
> The only alternative is to preload everything but include a default recipe system that requires manual enabling. That might be a little better for the user, but similarly that would be pretty complex on the development side.

Fair enough. The only idea that I had was to have some kind of screen where users can see all the recipes for a given item and select a single variant which will be used for all calculations. They can also change said variant on the same screen later on if they want to take advantage of better recipe ratios.

I can see that this is quite a lot of work to implement. Would you be willing to accept a PR if someone puts in the effort?

**Comment by Alexdoru** [comment]
> t a single variant which will be used for all calculations. They can also change said variant on the same screen later on if they want to take advantage of better recipe ratios.
> 
> I can see that this is quite a lot of work to implement. Would you be willing to accept a PR if someone puts in the effort?

yes of course we would accept PR for such a feature, that would be a nice addition :)

**Comment by PlayfulPiano** [comment]
> > There are multiple recipes for the same item output, some with cheaper or more expensive costs to generate. It would be extremely difficult if not impossible to have the mod automatically pick the correct recipe path for an item or specifically modulate the recipes based on what stage of the game you're in.
> > 
> > The best that can be done with this type of mod is have a set of default recipes pre loaded (emi does this), but even then that's usually limited to vanilla recipes as mod recipes are usually modpack specific.
> > 
> > E.g. iron ingots to iron plates either require a hammer and 2 ingots in a crafting table (stone age), 3 ingots in a forge hammer for 2 plates (steam age), or 1 ingot in a bender for 1 plate (LV). How would the mod calculate the recipe correctly here?
> > 
> > The only alternative is to preload everything but include a default recipe system that requires manual enabling. That might be a little better for the user, but similarly that would be pretty complex on the development side.
> 
> Fair enough. The only idea that I had was to have some kind of screen where users can see all the recipes for a given item and select a single variant which will be used for all calculations. They can also change said variant on the same screen later on if they want to take advantage of better recipe ratios.
> 
> I can see that this is quite a lot of work to implement. Would you be willing to accept a PR if someone puts in the effort?

Yeah of course. I would make a few suggestions on how to do that implementation though, if you plan to do so:

- use NEI for grabbing the available recipes. The mod already does so to begin with, might as well not duplicate the process (and increase load time).

- add the ability for user made named presets on what recipes are enabled/disabled, possibly also modpack made presets through its config.

- consider the ability to swap catalysts (i.e. the thing you use to do the craft, like specific machines or a crafting table). 

- lastly, and this would probably be the most difficult, including other recipe information like processing time or systematic concepts like energy or fluid generation/usage, and being able to determine like power reqs or total processing time

Good luck though, if you are planning to do a PR (or to anyone else who might read this)
