### ISSUE TITLE
Fluids don't work correctly

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/JustEnoughCalculation#20]
### Your GTNH Discord Username

impvt

### Mod Version

1.7.10-4.2

### Bug Report

It shows fluids the same way items, 2 of 576L and 12 of 288L polyethylene as different items and not combining them.
![image](https://github.com/user-attachments/assets/8f0e1702-fafb-45fd-8684-dec94161fd05)

### Java Version

Java 21

### Mod List or GTNH Pack Version

2.7.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by serenibyss** [comment]
Fixed in #18
